# Generated by Django 3.2.25 on 2026-02-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('complaint_categpry', models.CharField(max_length=45)),
                ('complaint_details', models.CharField(max_length=45)),
                ('reply', models.CharField(max_length=45)),
                ('teacher_id', models.CharField(max_length=45)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'complaint',
                'managed': False,
            },
        ),
    ]
