# Generated by Django 3.2.25 on 2026-02-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(db_column=' subject_name', max_length=45)),
                ('topic_name', models.CharField(max_length=45)),
                ('upload_document', models.CharField(max_length=1000)),
                ('teacher_id', models.IntegerField()),
            ],
            options={
                'db_table': 'document',
                'managed': False,
            },
        ),
    ]
