# Generated by Django 3.2.25 on 2026-02-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentRegister',
            fields=[
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('studentname', models.CharField(max_length=45)),
                ('department', models.CharField(max_length=45)),
                ('year', models.CharField(max_length=45)),
                ('registernumber', models.CharField(max_length=45)),
                ('contact', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('studentusername', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'parent_register',
                'managed': False,
            },
        ),
    ]
