# Generated by Django 3.2.25 on 2026-02-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoQuestions',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('subjectname', models.CharField(max_length=45)),
                ('topicname', models.CharField(max_length=45)),
                ('uploadvideo', models.CharField(max_length=1000)),
                ('uploadquestion', models.CharField(max_length=45)),
                ('teacher_id', models.IntegerField()),
            ],
            options={
                'db_table': 'video_questions',
                'managed': False,
            },
        ),
    ]
