# Generated by Django 3.2.25 on 2026-02-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentUpload',
            fields=[
                ('fn_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('upload_assignment', models.CharField(max_length=45)),
                ('upload_date', models.DateField()),
                ('grade', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'assignment_upload',
                'managed': False,
            },
        ),
    ]
