# Generated by Django 3.2.25 on 2026-02-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConductExam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=45)),
                ('department', models.CharField(max_length=45)),
                ('year', models.CharField(max_length=45)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('upload_question', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'conduct_exam',
                'managed': False,
            },
        ),
    ]
