# Generated by Django 3.2.25 on 2026-02-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('doubt_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('subject_name', models.CharField(max_length=45)),
                ('topic_name', models.CharField(max_length=45)),
                ('upload_doubt', models.CharField(max_length=45)),
                ('student_question', models.CharField(max_length=45)),
                ('reply', models.CharField(max_length=45)),
                ('teacher_id', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doubt',
                'managed': False,
            },
        ),
    ]
