# Generated by Django 3.2.25 on 2026-02-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_name', models.CharField(max_length=45)),
                ('assignment_subject', models.CharField(max_length=45)),
                ('assig_sublastdate', models.DateField()),
                ('teacher_id', models.IntegerField()),
            ],
            options={
                'db_table': 'assignment',
                'managed': False,
            },
        ),
    ]
